import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Header from './header';
import Footer from './Footer'
import styles from '../styles/Home.module.css';

const Layout = ({children, title, description}) =>  {

  return (
    <div className={`md`} >
      <Head>
        <title>APP | {title}</title>
        <meta name="description" content={description ?? "Generated by create next app"} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>

      <main className={styles.main}>
        {children}
      </main>
      <Footer />

    </div>
  )
}

export default  Layout;